### ISSUE TITLE
model checkpoints/weights release

### ISSUE THREAD

**Issue by russel0719** [IDEA-Research/Grounding-DINO-1.5-API#1]
Thank you for your great work!

Is there any plan to release the model checkpoint/weight files?

**Comment by Mountchicken** [comment]
Hi @russel0719 
Currently, we don't have a plan to release the code, but we are opening free access to the model API: https://github.com/IDEA-Research/Grounding-DINO-1.5-API?tab=readme-ov-file#api-usage

**Comment by russel0719** [comment]
> Hi @russel0719 Currently, we don't have a plan to release the code, but we are opening free access to the model API: https://github.com/IDEA-Research/Grounding-DINO-1.5-API?tab=readme-ov-file#api-usage

Hi @Mountchicken 
Oh, I see. Thank you for your reply!
