### ISSUE TITLE
About Edge model

### ISSUE THREAD

**Issue by TheMattBin** [IDEA-Research/Grounding-DINO-1.5-API#10]
So far I only play with the API token, I guess would be from Pro version, may I know if I can call Edge one?

**Comment by Mountchicken** [comment]
Hi @TheMattBin 
You can switch to Edge model at here:
![27701716276572_ pic](https://github.com/IDEA-Research/Grounding-DINO-1.5-API/assets/65173622/1e54e141-eac0-4d1c-bdd3-e9175fe4fc2b)
