### ISSUE TITLE
Request for model

### ISSUE THREAD

**Issue by tommyshelby4** [IDEA-Research/Grounding-DINO-1.5-API#12]
May I somehow be provided the model file to deploy it locally and maybe fine-tune it for a more specific task?

**Comment by rentainhe** [comment]
Sorry, we did not plan to release our weights at this time, but we may provide some fine-tuning or deploy service in the future.

**Comment by tommyshelby4** [comment]
For the time being, the model can only be used through the API right?

**Comment by garbe-github-support** [comment]
Don't provide a model. What source are you opening?  not interested in watching you act

**Comment by rentainhe** [comment]
> For the time being, the model can only be used through the API right?

Yes, at this version, we only release our API for Grounding DINO 1.5.

As we are exploring commercialization opportunities, we don't yet have a plan to release the model. But we are open to other ways for collaboration. Please let us know if you have any ideas or suggestions.
