### ISSUE TITLE
RuntimeError: Failed to trigger DetectionTask[None], error: Token out of Quota

### ISSUE THREAD

**Issue by kqdlx3** [IDEA-Research/Grounding-DINO-1.5-API#15]
rt，it seems reach the limit times of api call, how to get more?thank you

**Comment by rentainhe** [comment]
> rt，it seems reach the limit times of api call, how to get more?thank you

You can send another application and the system will automatically give you more tokens~

**Comment by rentainhe** [comment]
By the way, if it's convenient for you, could you tell us in what scenarios you use our model and how the model performance is? We will try to improve the user experience in the next version as much as possible.

**Comment by kqdlx3** [comment]
> > rt，it seems reach the limit times of api call, how to get more?thank you
> 
> You can provide the `email` or `username` you used when filling out the application form, and we will provide you more quota for usage. @kqdlx3

the email is 1397776343@qq.com, thank you so much

**Comment by kqdlx3** [comment]
> By the way, if it's convenient for you, could you tell us in what scenarios you use our model and how the model performance is? We will try to improve the user experience in the next version as much as possible.

I am using this model to generate pseudo-labels for autonomous driving scenarios， the model works well for detecting common targets such as vehicles and pedestrians, but encounters problems of false negatives and false positives when dealing with some uncommon categories (such as ground lane guidance arrows). This issue becomes more prominent in low-illumination environments.

**Comment by rentainhe** [comment]
> > > rt，it seems reach the limit times of api call, how to get more?thank you
> > 
> > 
> > You can provide the `email` or `username` you used when filling out the application form, and we will provide you more quota for usage. @kqdlx3
> 
> the email is [1397776343@qq.com](mailto:1397776343@qq.com), thank you so much

Got it! We've already assign 500 quotas for you to call our API, and you can also check the email for more details.

**Comment by rentainhe** [comment]
> > By the way, if it's convenient for you, could you tell us in what scenarios you use our model and how the model performance is? We will try to improve the user experience in the next version as much as possible.
> 
> I am using this model to generate pseudo-labels for autonomous driving scenarios， the model works well for detecting common targets such as vehicles and pedestrians, but encounters problems of false negatives and false positives when dealing with some uncommon categories (such as ground lane guidance arrows). This issue becomes more prominent in low-illumination environments.

Thank you so much for your feedback, I was curious about the `ground lane guidance arrow`. You need the model to detect specific lane guidance arrow name or just a general category like `traffic sign`

**Comment by kqdlx3** [comment]
thank you so much。
&nbsp;


Glory&nbsp;Of&nbsp;Train
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ren ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 上午10:43
收件人: ***@***.***&gt;; 
抄送: "Glory Of ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IDEA-Research/Grounding-DINO-1.5-API] RuntimeError: Failed to trigger DetectionTask[None], error: Token out of Quota (Issue #15)














    
rt，it seems reach the limit times of api call, how to get more?thank you
  
You can provide the email or username you used when filling out the application form, and we will provide you more quota for usage. @kqdlx3
  
the email is ***@***.***, thank you so much
  
Got it! We've already assign 500 quotas for you to call our API, and you can also check the email for more details.

**Comment by kqdlx3** [comment]
just a general category，for example turn left, trun right, forward direct. the are a category
&nbsp;


Glory&nbsp;Of&nbsp;Train
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ren ***@***.***&gt;; 
发送时间: 2024年5月24日(星期五) 上午10:45
收件人: ***@***.***&gt;; 
抄送: "Glory Of ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [IDEA-Research/Grounding-DINO-1.5-API] RuntimeError: Failed to trigger DetectionTask[None], error: Token out of Quota (Issue #15)














   
By the way, if it's convenient for you, could you tell us in what scenarios you use our model and how the model performance is? We will try to improve the user experience in the next version as much as possible.
  
I am using this model to generate pseudo-labels for autonomous driving scenarios， the model works well for detecting common targets such as vehicles and pedestrians, but encounters problems of false negatives and false positives when dealing with some uncommon categories (such as ground lane guidance arrows). This issue becomes more prominent in low-illumination environments.
  
Thank you so much for your feedback, I was curious about the ground lane guidance arrow. You need the model to detect specific lane guidance arrow name or just a general category like traffic sign

**Comment by rentainhe** [comment]
> just a general category，for example turn left, trun right, forward direct. the are a category &nbsp; Glory&nbsp;Of&nbsp;Train ***@***.*** &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "Ren ***@***.***&gt;; 发送时间: 2024年5月24日(星期五) 上午10:45 收件人: ***@***.***&gt;; 抄送: "Glory Of ***@***.***&gt;; ***@***.***&gt;; 主题: Re: [IDEA-Research/Grounding-DINO-1.5-API] RuntimeError: Failed to trigger DetectionTask[None], error: Token out of Quota (Issue #15) By the way, if it's convenient for you, could you tell us in what scenarios you use our model and how the model performance is? We will try to improve the user experience in the next version as much as possible. I am using this model to generate pseudo-labels for autonomous driving scenarios， the model works well for detecting common targets such as vehicles and pedestrians, but encounters problems of false negatives and false positives when dealing with some uncommon categories (such as ground lane guidance arrows). This issue becomes more prominent in low-illumination environments. Thank you so much for your feedback, I was curious about the ground lane guidance arrow. You need the model to detect specific lane guidance arrow name or just a general category like traffic sign — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***&gt;

Thanks for your feedback!
