### ISSUE TITLE
Huggingface demo error

### ISSUE THREAD

**Issue by VamsiYK** [IDEA-Research/Grounding-DINO-1.5-API#16]
Please fix hf  demo for inference. Thanks.

**Comment by rentainhe** [comment]
> Please fix hf demo for inference. Thanks.

We will fix it as soon as possible

**Comment by rentainhe** [comment]
The quota of the huggingface demo API is running out, maybe you can try G-DINO 1.5 Pro in our DDS platform with free quotas by requesting the API token: https://github.com/IDEA-Research/Grounding-DINO-1.5-API?tab=readme-ov-file#2-request-api-from-deepdataspace
