### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by benedikt-schesch** [IDEA-Research/Grounding-DINO-1.5-API#18]
Hello,

Thank you for this great model.
Do you plan to release the weights and code of this model to the public? If yes do you have an idea of the timeline?

**Comment by rentainhe** [comment]
Hello, thanks for your attention to our work.

As we are exploring commercialization opportunities, we don't yet have a plan to release the model. But we are open to other ways for collaboration. Please let us know if you have any ideas or suggestions.
