### ISSUE TITLE
RuntimeError: DetectionTask[4f3e1086-4aea-40d8-9ad0-2428a64850fc]  is failed, error:

### ISSUE THREAD

**Issue by Xiaolong-RRL** [IDEA-Research/Grounding-DINO-1.5-API#19]
Dear author:

Thanks for your interesting work.

When I run the Grounding-Dino-1.5-API with DetectionTask, an error happend:
![image](https://github.com/IDEA-Research/Grounding-DINO-1.5-API/assets/74476562/a78dcc98-0d39-49eb-8220-3d47c24e0adf)

the code is:
```python
# 1. Initialize the client with your API token.
from dds_cloudapi_sdk import Config
from dds_cloudapi_sdk import Client
from dds_cloudapi_sdk import DetectionTask
from dds_cloudapi_sdk import TextPrompt
from dds_cloudapi_sdk import DetectionModel
from dds_cloudapi_sdk import DetectionTarget
from API_KEYS import dds_cloudapi_sdk_token

# Step 1: initialize the config
token = 'xxx'
config = Config(token)

# Step 2: initialize the client
client = Client(config)

# Step 3: run the task by DetectionTask class
image_url = "temp/vl_three_objects.jpg"
# if you are processing local image file, upload them to DDS server to get the image url
# image_url = client.upload_file("/path/to/your/prompt/image.png")

task = DetectionTask(
    image_url=image_url,
    prompts=[TextPrompt(text="Remote control")],
    targets=[DetectionTarget.Mask, DetectionTarget.BBox],  # detect both bbox and mask
    model=DetectionModel.GDino1_5_Pro,  # detect with GroundingDino-1.5-Pro model
)

client.run_task(task)
result = task.result

print(result.mask_url)

objects = result.objects  # the list of detected objects
for idx, obj in enumerate(objects):
    print(obj.score)  # 0.42

    print(obj.category)  # "iron man"

    print(obj.bbox)  # [635.0, 458.0, 704.0, 508.0]

    print(obj.mask.counts)  # RLE compressed to string, ]o`f08fa14M3L2O2M2O1O1O1O1N2O1N2O1N2N3M2O3L3M3N2M2N3N1N2O...

    # convert the RLE format to RGBA image
    mask_image = task.rle2rgba(obj.mask)
    print(mask_image.size)  # (1600, 1170)

    # save the image to file
    mask_image.save(f"{image_url[:-4]}_mask_{idx}.jpg")

    break
```
and I wander how to solve it?

**Comment by rentainhe** [comment]
> token = 'xxx'

Have you ever check your token ID here, maybe you should apply for API tokens first and replace `xxx` with your own token for API usage

**Comment by Xiaolong-RRL** [comment]
> > token = 'xxx'
> 
> Have you ever check your token ID here, maybe you should apply for API tokens first and replace `xxx` with your own token for API usage

yes, this error happened with the API tokens that I have applied

**Comment by rentainhe** [comment]
> > > token = 'xxx'
> > 
> > 
> > Have you ever check your token ID here, maybe you should apply for API tokens first and replace `xxx` with your own token for API usage
> 
> yes, this error happened with the API tokens that I have applied

have you ever checked your local image path, make sure it can be reached by your code

**Comment by Xiaolong-RRL** [comment]
I should upload my local image file to DDS server to get the image url:
```image_url = client.upload_file("/path/to/your/prompt/image.png")```
And it works, thanks for your kindly reply～
