### ISSUE TITLE
Token exceeds Rate Limit

### ISSUE THREAD

**Issue by Rio-Allen** [IDEA-Research/Grounding-DINO-1.5-API#23]
Excellent job!
I am wondering what is the rate limit for token calls? Is there any solution to raise the rate limit?

**Comment by rentainhe** [comment]
> Excellent job! I am wondering what is the rate limit for token calls? Is there any solution to raise the rate limit?

@Rio-Allen We have set limited tokens for the users to use our model at the first time, if you need more quotas, feel free to contact us through this email: rentianhe@idea.edu.cn

**Comment by Rio-Allen** [comment]
已收到您的来信，谢谢!   ——徐锐豪
