### ISSUE TITLE
Florence-2发布了，看起来各方面比Grounding-DINO-1.5优秀咧

### ISSUE THREAD

**Issue by Pillar1989** [IDEA-Research/Grounding-DINO-1.5-API#29]

**Comment by SlongLiu** [comment]
感谢对我们工作的关注！

我们认为Florence-2也是非常好的工作，也很高兴看到用户能够有不同的选择。我们欢迎社区成员亲自尝试这些模型，并分享您的使用体验。

Grounding-DINO-1.5和Florence-2采用了不同的技术方法，各有其独特的优势。我们建议用户根据具体的应用场景和需求来选择最适合的模型。

在我们的内部测试中，Grounding-DINO-1.5的检测能力更强。在COCO zero-shot检测上的指标也可以作为参考，Grounding-DINO-1.5达到了54.3的分数，而Florence-2为43.4。

我们期待看到更多创新成果，共同推动计算机视觉领域的发展。


Thank you for your interest in our work!

We believe Florence-2 is also an excellent contribution to the field, and we're pleased to see users have different options to choose from.

Grounding-DINO-1.5 and Florence-2 employ different technical approaches. We recommend users select the most suitable model based on their specific application scenarios and requirements.

In our internal evaluations, Grounding-DINO-1.5 demonstrated stronger detection capabilities. For reference, on the COCO zero-shot detection benchmark, Grounding-DINO-1.5 achieved a score of 54.3, while Florence-2 scored 43.4.

We look forward to seeing more innovative achievements and working together to advance the field of computer vision.

**Comment by sunhaha123** [comment]
优秀个p，你都测了吗？
