### ISSUE TITLE
Claim your paper and engage with the community 🤗

### ISSUE THREAD

**Issue by adeenayakup** [IDEA-Research/Grounding-DINO-1.5-API#3]
Hi! 
Congrats on Grounding DIO 1.5, really cool work 🔥🚀
It would be great to claim your [paper](https://huggingface.co/papers/2405.10300) on our [Daily Paper Page](https://huggingface.co/papers). There are already comments on the paper threads : )
Feel free to engage with the community and to get more feedbacks!

**Comment by rentainhe** [comment]
Thank you for the reminder! We will follow up on this and claim our work. We also look forward to the community's feedback on our work!
