### ISSUE TITLE
API返回结果

### ISSUE THREAD

**Issue by Carloslius** [IDEA-Research/Grounding-DINO-1.5-API#44]
您好，非常感谢您出色的成果，1.6Pro版本的检测结果精确的让我难以置信！
但美中不足的是，目前API返回的结果task.result中，好像只有bbox,score和对应的category，我现在想要拿到每个bbox中物体的图像和文本特征，而不只是score和category，请问您可以在API的返回结果中添加对应的图像和文本特征吗？万分感激您！

**Comment by rentainhe** [comment]
您好，这边我们暂时在API中还不考虑支持直接返回模型提取的特征，如果您有相关方面的实际应用需求的话非常欢迎您通过邮件联系我们，针对一些实际的情况进行线下的讨论，这边您有需要的话可以发送邮件到: rentianhe@idea.edu.cn

**Comment by Carloslius** [comment]
> @Carloslius 您好，这边我们暂时在API中还不考虑支持直接返回模型提取的特征，如果您有相关方面的实际应用需求的话非常欢迎您通过邮件联系我们，针对一些实际的情况进行线下的讨论，这边您有需要的话可以发送邮件到: [rentianhe@idea.edu.cn](mailto:rentianhe@idea.edu.cn)

好的，谢谢您的回复
