### ISSUE TITLE
Token exceeds Rate Limit

### ISSUE THREAD

**Issue by wzhiyuan2016** [IDEA-Research/Grounding-DINO-1.5-API#9]
![企业微信截图_17162025131025](https://github.com/IDEA-Research/Grounding-DINO-1.5-API/assets/33740622/f34d86b9-ddcd-41de-aa8d-2180173b33c4)
我想批量跑500张图，测试一下效果。发现读取文件夹内500张图，只能跑5张图。不是申请到的Token 有200 次 免费 API 调用么 谢谢

**Comment by rentainhe** [comment]
我们在后台访问的时候限制了访问频率，这边最快的速度是不超过10次/s，所以可以考虑串行请求或者设置一些time.sleep控制一下请求频率看看是否可以解决这个问题

**Comment by wzhiyuan2016** [comment]
okey thank you

**Comment by wzhiyuan2016** [comment]
> 我们在后台访问的时候限制了访问频率，这边最快的速度是不超过10次/s，所以可以考虑串行请求或者设置一些time.sleep控制一下请求频率看看是否可以解决这个问题
okey thank you

**Comment by rentainhe** [comment]
> > 我们在后台访问的时候限制了访问频率，这边最快的速度是不超过10次/s，所以可以考虑串行请求或者设置一些time.sleep控制一下请求频率看看是否可以解决这个问题
> > okey thank you

You're welcome

**Comment by yutao007** [comment]
两个大兄弟，最后怎么标出英文了。杰伦都说过：华流才是最吊的。
